apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-tc6r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-tc6r
    app.kubernetes.io/part-of: tkwch-fix-0075-0041-app
  name: devfile-sample-tc6r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-tc6r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-tc6r
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-22-tenant/tkwch-fix-0075-0041-app/devfile-sample-tc6r@sha256:e9ecd57daff1b2a6437721992f09061eb57a698222a72c35495afe5084387e96
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
